# Generated by Django 5.2.4 on 2025-07-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('available_sizes', models.JSONField(default=list)),
                ('available_colors', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('accessories', 'Accessories'), ('footwear', 'Footwear'), ('sportswear', 'Sportswear'), ('formal', 'Formal'), ('casual', 'Casual'), ('ethnic', 'Ethnic'), ('partywear', 'Partywear'), ('winterwear', 'Winterwear'), ('undergarments', 'Undergarments'), ('sleepwear', 'Sleepwear'), ('activewear', 'Activewear'), ('swimwear', 'Swimwear')], max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_new', models.BooleanField(default=False, verbose_name='New')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='On Sale')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='Best Seller')),
                ('care_instructions', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('shipping_info', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Supported formats: JPEG, PNG, WebP, GIF', upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='product_videos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Video',
                'verbose_name_plural': 'Product Videos',
                'ordering': ['id'],
            },
        ),
    ]
