# Generated by Django 5.2.4 on 2025-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(choices=[('product_inquiry', 'Product Inquiry'), ('order_status', 'Order Status'), ('sizing_help', 'Sizing Help'), ('styling_advice', 'Styling Advice'), ('return_exchange', 'Return/Exchange'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('wholesale', 'Wholesale Inquiry'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('newsletter_signup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
